SFH3_NAME=Free-For-All
SFH3_MODE=dm
SFH3_MAP=cqc
SFH3_ROTATION=cqc,construction,cavesb,canyon,street
SFH3_MODES=dm,gg,one
SFH3_SCORE=15
SFH3_MOD=none
SFH3_BOTS=7
SFH3_BOTLEVEL=10
SFH3_MAX=10
SFH3_TIMELIMIT=480
SFH3_COOP=0
SFH3_KIND=normal
