SFH3_NAME=Capture the Flag
SFH3_MODE=ctf
SFH3_MAP=street
SFH3_ROTATION=street,temple,gorge,junkyard,caves
SFH3_MODES=
SFH3_SCORE=3
SFH3_MOD=none
SFH3_BOTS=8
SFH3_BOTLEVEL=14
SFH3_MAX=12
SFH3_TIMELIMIT=900
SFH3_COOP=0
SFH3_KIND=normal
