SFH3_NAME=Ranked
SFH3_KIND=ranked
SFH3_COOP=0
SFH3_MODE=tdm
SFH3_MAP=forest
SFH3_ROTATION=volcano,forest,factory,canyon,frigate
SFH3_MODES=
SFH3_SCORE=25
SFH3_MOD=none
SFH3_BOTS=0
SFH3_BOTLEVEL=14
SFH3_MAX=10
SFH3_TIMELIMIT=600
